language: node_js
node_js:
- '9'
- '10'

jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email: bennny@noqcks.io
      api_key:
        secure: ZFw16vNCgLp/RPPQ39XfcUhPirJnkep3mavspHnIM6EY5dCKRIHZxLYk+TceTzl5AyzvZotJPbTimulv6lxQD72XTKmgB+iMNrPPj/t/v/VjGb1kMC1TY2jxzkpaqeffqaRC8R6/quTWJTNOn1Sw/TiuS/t3B5aRq+3AkYx/DmJ5XIzLb9KZwrASkI2ZNQPGdnGbknGKnTihf4bHlOTCFIue1RnyIoAE96Z6h7ky5D9XP3MWVQFz9TLBNUastp6/3sbu5M9l57P6tHen6I+5tsaOmJzGWxL+QLKFHhlE//70beRl0B1VupHRxH3IT7h1nFJvBCM/TeXA/sxxFaTzTVmtU2HyPCQblJzL6fiI3hRLLd3cLvQ2YugD+swoPSQjqRGUPZoSsv7X8cZaDMY9zz2yPJv8dWnxXmSJcymYGeHTL1bsv/GPCDA8iaGy49jqkmb+WEBD9q8+QNVbTyFlvBxku23+a7c+1o8FyS9JtFUDMbv9mI/szvxubDBeBlf99ft6JINoZyo7wkhE+bGspAwDaaZizOInXLh0SqUZ3iSYX6bsQTQLrZNsbsyzBKRVtfgC49gtg1F6263jCzAo2DiAJxn3bi11FYKecukmQ1vnZMuiOgXMQ6sDoCosm1Kzyo1JUevxHn+v7MCdTkmVMNoOiVt84wPj4PIPzWYFq6k=
      on:
        tags: true
        repo: noqcks/generated
